INSERT INTO delays (year, month, cause, count, description, incidents, observations) VALUES
(2025, 'Enero', 'Repercusión', 333, 'Se origina en otros aeropuertos y su consecuente llegada tardía al AIFA.', ARRAY[]::TEXT[], ''),
(2025, 'Enero', 'Compañía', 203, 'Las principales causas son mantenimiento no programado, espera de tripulación, conveniencia de la aerolínea y flujo lento de pasajeros.', ARRAY[]::TEXT[], ''),
(2025, 'Enero', 'Evento Circunstancial', 41, 'Se origina por pasajeros disruptivos, pasajeros o tripulantes enfermos, pasajeros con poca movilidad, así como, espera por tráfico aéreo.', ARRAY[]::TEXT[], ''),
(2025, 'Enero', 'Combustible', 4, 'Demoras causadas por disponibilidad o gestión de combustible.', ARRAY[]::TEXT[], 'Se originó por la llegada tarde del dispensador y error de personal en la recarga de combustible.'),
(2025, 'Enero', 'Autoridad', 2, 'Demoras relacionadas con inspecciones o procesos a cargo de la autoridad.', ARRAY['M76333 del 29 de enero','M7851 del 31 de enero'], 'Aduanas no contaba con revisión de rayos X, se realiza con binomios Canófilos'),
(2025, 'Enero', 'Meteorología', 37, 'Sucede por esperar mejores condiciones meteorológicas en el aeropuerto de destino, principalmente lluvia y bancos de niebla.', ARRAY[]::TEXT[], ''),
(2025, 'Enero', 'Aeropuerto', 1, 'Demoras derivadas de infraestructura o servicios del propio aeropuerto.', ARRAY['VB7282 del 29 del 06 de enero'], 'Demora de 27 minutos por falla de pasillo en la posición 106B.
1. Se detectó pasillo bloqueado por alarma del sistema anticolisión, este es reiniciado por el operador sin resultado positivo, informando a Ingeniería Electromecánica la cual evalúa la falla, no encontrando solución al momento, determinando necesario el cambio de posición.
2. CCO a fin de evitar generar una mayor demora, coordina con la aerolínea el cambio de posición a 106A.
3. La aeronave es remocalada a posición 106A y continúa con su proceso de desembarque, generando una demora total de 27 minutos.'),
(2025, 'Febrero', 'Repercusión', 204, 'Se origina en otros aeropuertos y su consecuente llegada tardía al AIFA.', ARRAY[]::TEXT[], ''),
(2025, 'Febrero', 'Compañía', 167, 'Las principales causas son mantenimiento no programado, espera de tripulación, conveniencia de la aerolínea y flujo lento de pasajeros.', ARRAY[]::TEXT[], ''),
(2025, 'Febrero', 'Evento Circunstancial', 12, 'Se origina por pasajeros disruptivos, pasajeros o tripulantes enfermos, pasajeros con poca movilidad, así como, espera por tráfico aéreo.', ARRAY[]::TEXT[], 'No hubo demoras'),
(2025, 'Febrero', 'Combustible', 0, 'Demoras causadas por disponibilidad o gestión de combustible.', ARRAY[]::TEXT[], 'No hubo demoras'),
(2025, 'Febrero', 'Autoridad', 2, 'Demoras relacionadas con inspecciones o procesos a cargo de la autoridad.', ARRAY['M76810 del 02 de febrero','M76710 del 15 de febrero'], 'Aduanas no contaba con revisión de rayos X, se realiza con binomios Canófilos'),
(2025, 'Febrero', 'Meteorología', 22, 'Sucede por esperar mejores condiciones meteorológicas en el aeropuerto de destino, principalmente lluvia y bancos de niebla.', ARRAY[]::TEXT[], ''),
(2025, 'Febrero', 'Aeropuerto', 0, 'Demoras derivadas de infraestructura o servicios del propio aeropuerto.', ARRAY[]::TEXT[], 'No hubo demoras'),
(2025, 'Marzo', 'Repercusión', 288, 'Se origina en otros aeropuertos y su consecuente llegada tardía al AIFA.', ARRAY[]::TEXT[], ''),
(2025, 'Marzo', 'Compañía', 207, 'Las principales causas son mantenimiento no programado, espera de tripulación, conveniencia de la aerolínea y flujo lento de pasajeros.', ARRAY[]::TEXT[], ''),
(2025, 'Marzo', 'Evento Circunstancial', 12, 'Se origina por pasajeros disruptivos, pasajeros o tripulantes enfermos, pasajeros con poca movilidad, así como, espera por tráfico aéreo.', ARRAY[]::TEXT[], ''),
(2025, 'Marzo', 'Combustible', 9, 'Demoras causadas por disponibilidad o gestión de combustible.', ARRAY[]::TEXT[], ''),
(2025, 'Marzo', 'Autoridad', 0, 'Demoras relacionadas con inspecciones o procesos a cargo de la autoridad.', ARRAY[]::TEXT[], ''),
(2025, 'Marzo', 'Meteorología', 7, 'Sucede por esperar mejores condiciones meteorológicas en el aeropuerto de destino, principalmente lluvia y bancos de niebla.', ARRAY[]::TEXT[], ''),
(2025, 'Marzo', 'Aeropuerto', 2, 'Demoras derivadas de infraestructura o servicios del propio aeropuerto.', ARRAY['Vuelo Y43533 deL 03 de marzo','Vuelo AM588 del 07 de marzo'], 'Demora de 39 minutos, por falla eléctrica en el pasillo de la posición 111A.
1.- NOTA: Con el fin de evitar demoras por fallas de aeropasillos en lo subsecuente, esta Dirección realizará procedimientos para efectuar el retroceso de la aeronave con el pasillo conectado cuando fallen, priorizando la Seguridad Operacional'),
(2025, 'Abril', 'Repercusión', 406, 'Se origina en otros aeropuertos y su consecuente llegada tardía al AIFA.', ARRAY[]::TEXT[], ''),
(2025, 'Abril', 'Compañía', 225, 'Las principales causas son mantenimiento no programado, espera de tripulación, conveniencia de la aerolínea y flujo lento de pasajeros.', ARRAY[]::TEXT[], ''),
(2025, 'Abril', 'Evento Circunstancial', 35, 'Se origina por pasajeros disruptivos, pasajeros o tripulantes enfermos, pasajeros con poca movilidad, así como, espera por tráfico aéreo.', ARRAY[]::TEXT[], ''),
(2025, 'Abril', 'Combustible', 5, 'Demoras causadas por disponibilidad o gestión de combustible.', ARRAY['Vuelo VB7333 del 11 de Abril (25 minutos).','Vuelo VB5067 del 14 de Abril (25 minutos).','Vuelo VB2287 del 16 de Abril (20 minutos).','Vuelo E7615 del 17 de Abril (47 minutos).','Vuelo VB2279 del 19 de Abril (41 minutos).'], ''),
(2025, 'Abril', 'Autoridad', 2, 'Demoras relacionadas con inspecciones o procesos a cargo de la autoridad.', ARRAY['M78323 del 15 de abril (23 minutos)','M78361 del 26 de abril (27 minutos)'], ''),
(2025, 'Abril', 'Meteorología', 0, 'Sucede por esperar mejores condiciones meteorológicas en el aeropuerto de destino, principalmente lluvia y bancos de niebla.', ARRAY[]::TEXT[], 'No hubo demoras'),
(2025, 'Abril', 'Aeropuerto', 0, 'Demoras derivadas de infraestructura o servicios del propio aeropuerto.', ARRAY[]::TEXT[], 'No hubo demoras'),
(2025, 'Mayo', 'Repercusión', 384, 'Se origina en otros aeropuertos y su consecuente llegada tardía al AIFA.', ARRAY[]::TEXT[], ''),
(2025, 'Mayo', 'Compañía', 199, 'Las principales causas son mantenimiento no programado, espera de tripulación, conveniencia de la aerolínea y flujo lento de pasajeros.', ARRAY[]::TEXT[], ''),
(2025, 'Mayo', 'Evento Circunstancial', 5, 'Se origina por pasajeros disruptivos, pasajeros o tripulantes enfermos, pasajeros con poca movilidad, así como, espera por tráfico aéreo.', ARRAY[]::TEXT[], ''),
(2025, 'Mayo', 'Combustible', 1, 'Demoras causadas por disponibilidad o gestión de combustible.', ARRAY['Vuelo LH8223 del 02 de mayo (21 minutos).'], 'Por falta de dispensadores de combustible.'),
(2025, 'Mayo', 'Autoridad', 0, 'Demoras relacionadas con inspecciones o procesos a cargo de la autoridad.', ARRAY[]::TEXT[], 'No hubo demoras'),
(2025, 'Mayo', 'Meteorología', 1054, 'Sucede por esperar mejores condiciones meteorológicas en el aeropuerto de destino, principalmente lluvia y bancos de niebla.', ARRAY[]::TEXT[], ''),
(2025, 'Mayo', 'Aeropuerto', 1, 'Demoras derivadas de infraestructura o servicios del propio aeropuerto.', ARRAY['Vuelo XN1264 del 04 de mayo (47 minutos).'], 'Por falla del sistema hidráulico para el movimiento de traslación, ascenso y descenso de pasillo telescópico en la posición 108A .'),
(2025, 'Junio', 'Repercusión', 414, 'Se origina en otros aeropuertos y su consecuente llegada tardía al AIFA.', ARRAY[]::TEXT[], ''),
(2025, 'Junio', 'Compañía', 123, 'Las principales causas son mantenimiento no programado, espera de tripulación, conveniencia de la aerolínea y flujo lento de pasajeros.', ARRAY[]::TEXT[], ''),
(2025, 'Junio', 'Evento Circunstancial', 3, 'Se origina por pasajeros disruptivos, pasajeros o tripulantes enfermos, pasajeros con poca movilidad, así como, espera por tráfico aéreo.', ARRAY[]::TEXT[], ''),
(2025, 'Junio', 'Combustible', 4, 'Demoras causadas por disponibilidad o gestión de combustible.', ARRAY['Vuelo M76471 del 01 de junio (34 minutos), llegada tardía del dispensador.','Vuelo VB7447 del 09 de junio (22 minutos), llegada tardía del dispensador.','Vuelo QR8813 del 12 de junio (24 minutos), llegada tardía del dispensador.','Vuelo 6471 del 15 de junio (27 minutos), carga lenta de combustible.'], ''),
(2025, 'Junio', 'Autoridad', 4, 'Demoras relacionadas con inspecciones o procesos a cargo de la autoridad.', ARRAY['LH8225 del 09 de junio (48 minutos). Inspección lenta de la carga','M76850 del 13 de junio (23 minutos). Inspección tardía de carga','5X321 del 16 de junio (36 minutos). Falta de equipo de Rayos X','M73114 del 30 de junio (45 minutos). Carga lenta de combustible'], ''),
(2025, 'Junio', 'Meteorología', 17, 'Sucede por esperar mejores condiciones meteorológicas en el aeropuerto de destino, principalmente lluvia y bancos de niebla.', ARRAY[]::TEXT[], ''),
(2025, 'Junio', 'Aeropuerto', 2, 'Demoras derivadas de infraestructura o servicios del propio aeropuerto.', ARRAY['Vuelo VB842 de fecha 21 de junio (53 minutos) por el restablecimiento de comunicación en sistemas de aeropasillo por la vibración que se genera en la operación (conector se desconectó debido al uso)','Vuelo VB3287 de fecha 25 de junio (23 minutos) por llegada tardía del Agente de de Guardia Nacional para la apertura de esclusas'], '1. Se está gestionando para que la empresa tome una capacitación con el proveedor del aeropasillo para prevenir este tipo de fallas
2. Se están automatizando las esclusas para evitar las demoras por los operadores de las esclusas '),
(2025, 'Julio', 'Repercusión', 503, 'Se origina en otros aeropuertos y su consecuente llegada tardía al AIFA.', ARRAY[]::TEXT[], ''),
(2025, 'Julio', 'Compañía', 154, 'Las principales causas son mantenimiento no programado, espera de tripulación, conveniencia de la aerolínea y flujo lento de pasajeros.', ARRAY[]::TEXT[], ''),
(2025, 'Julio', 'Evento Circunstancial', 9, 'Se origina por pasajeros disruptivos, pasajeros o tripulantes enfermos, pasajeros con poca movilidad, así como, espera por tráfico aéreo.', ARRAY[]::TEXT[], ''),
(2025, 'Julio', 'Combustible', 6, 'Demoras causadas por disponibilidad o gestión de combustible.', ARRAY[]::TEXT[], ''),
(2025, 'Julio', 'Autoridad', 7, 'Demoras relacionadas con inspecciones o procesos a cargo de la autoridad.', ARRAY[]::TEXT[], ''),
(2025, 'Julio', 'Meteorología', 28, 'Sucede por esperar mejores condiciones meteorológicas en el aeropuerto de destino, principalmente lluvia y bancos de niebla.', ARRAY[]::TEXT[], ''),
(2025, 'Julio', 'Aeropuerto', 0, 'Demoras derivadas de infraestructura o servicios del propio aeropuerto.', ARRAY[]::TEXT[], ''),
(2025, 'Agosto', 'Repercusión', 218, 'Se origina en otros aeropuertos y su consecuente llegada tardía al AIFA.', ARRAY[]::TEXT[], ''),
(2025, 'Agosto', 'Compañía', 190, 'Las principales causas son mantenimiento no programado, espera de tripulación, conveniencia de la aerolínea y flujo lento de pasajeros.', ARRAY[]::TEXT[], ''),
(2025, 'Agosto', 'Evento Circunstancial', 8, 'Se origina por pasajeros disruptivos, pasajeros o tripulantes enfermos, pasajeros con poca movilidad, así como, espera por tráfico aéreo.', ARRAY[]::TEXT[], ''),
(2025, 'Agosto', 'Combustible', 5, 'Demoras causadas por disponibilidad o gestión de combustible.', ARRAY['Vuelo K4810 deL 08 de agosto (101 minutos).','Vuelo AF6723 del 08 de agosto (86 minutos)','Vuelo CV5166 del 09 de agosto (19 minutos)','Vuelo VB7283  del 13 de agosto (48 minutos)','Vuelo ET3516 del 13 de agosto (74 minutos)'], 'Demoras por operaciones simultaneas y baja presión del dispensador D-166'),
(2025, 'Agosto', 'Autoridad', 4, 'Demoras relacionadas con inspecciones o procesos a cargo de la autoridad.', ARRAY['M78721 del 12 de agosto (52 minutos).','M78741 del 15 de agosto (37 minutos).','M78361 del 16 de agosto (55 minutos).','M78741 del 21 de agosto (173 minutos).'], 'Inspección tardía por falta de de equipo de Rayos X e inspección con binomios canófilos'),
(2025, 'Agosto', 'Meteorología', 199, 'Sucede por esperar mejores condiciones meteorológicas en el aeropuerto de destino, principalmente lluvia y bancos de niebla.', ARRAY[]::TEXT[], ''),
(2025, 'Agosto', 'Aeropuerto', 4, 'Demoras derivadas de infraestructura o servicios del propio aeropuerto.', ARRAY['Vuelo Y43297 deL 11 de agosto (65 minutos).','Vuelo VB5068 de fecha 11 de agosto (26 minutos).','Vuelo VB7344 de fecha 13 de agosto (49 minutos).','Vuelo VB7332 de fecha 19 de agosto (24 minutos).'], ''),
(2025, 'Septiembre', 'Repercusión', 319, 'Se origina en otros aeropuertos y su consecuente llegada tardía al AIFA.', ARRAY[]::TEXT[], ''),
(2025, 'Septiembre', 'Compañía', 158, 'Las principales causas son mantenimiento no programado, espera de tripulación, conveniencia de la aerolínea y flujo lento de pasajeros.', ARRAY[]::TEXT[], ''),
(2025, 'Septiembre', 'Evento Circunstancial', 7, 'Se origina por pasajeros disruptivos, pasajeros o tripulantes enfermos, pasajeros con poca movilidad, así como, espera por tráfico aéreo.', ARRAY[]::TEXT[], ''),
(2025, 'Septiembre', 'Combustible', 3, 'Demoras causadas por disponibilidad o gestión de combustible.', ARRAY[]::TEXT[], ''),
(2025, 'Septiembre', 'Autoridad', 5, 'Demoras relacionadas con inspecciones o procesos a cargo de la autoridad.', ARRAY[]::TEXT[], ''),
(2025, 'Septiembre', 'Meteorología', 4, 'Sucede por esperar mejores condiciones meteorológicas en el aeropuerto de destino, principalmente lluvia y bancos de niebla.', ARRAY[]::TEXT[], ''),
(2025, 'Septiembre', 'Aeropuerto', 0, 'Demoras derivadas de infraestructura o servicios del propio aeropuerto.', ARRAY[]::TEXT[], 'No hubo demoras'),
(2025, 'Octubre', 'Repercusión', 479, 'Se origina en otros aeropuertos y su consecuente llegada tardía al AIFA.', ARRAY[]::TEXT[], ''),
(2025, 'Octubre', 'Compañía', 164, 'Las principales causas son mantenimiento no programado, espera de tripulación, conveniencia de la aerolínea y flujo lento de pasajeros.', ARRAY[]::TEXT[], ''),
(2025, 'Octubre', 'Evento Circunstancial', 4, 'Se origina por pasajeros disruptivos, pasajeros o tripulantes enfermos, pasajeros con poca movilidad, así como, espera por tráfico aéreo.', ARRAY[]::TEXT[], ''),
(2025, 'Octubre', 'Combustible', 2, 'Demoras causadas por disponibilidad o gestión de combustible.', ARRAY[]::TEXT[], ''),
(2025, 'Octubre', 'Autoridad', 4, 'Demoras relacionadas con inspecciones o procesos a cargo de la autoridad.', ARRAY[]::TEXT[], ''),
(2025, 'Octubre', 'Meteorología', 13, 'Sucede por esperar mejores condiciones meteorológicas en el aeropuerto de destino, principalmente lluvia y bancos de niebla.', ARRAY[]::TEXT[], ''),
(2025, 'Octubre', 'Aeropuerto', 1, 'Demoras derivadas de infraestructura o servicios del propio aeropuerto.', ARRAY[]::TEXT[], ''),
(2025, 'Noviembre', 'Repercusión', 507, 'Se origina en otros aeropuertos y su consecuente llegada tardía al AIFA.', ARRAY[]::TEXT[], ''),
(2025, 'Noviembre', 'Compañía', 190, 'Las principales causas son mantenimiento no programado, espera de tripulación, conveniencia de la aerolínea y flujo lento de pasajeros.', ARRAY[]::TEXT[], ''),
(2025, 'Noviembre', 'Evento Circunstancial', 3, 'Se origina por pasajeros disruptivos, pasajeros o tripulantes enfermos, pasajeros con poca movilidad, así como, espera por tráfico aéreo.', ARRAY[]::TEXT[], ''),
(2025, 'Noviembre', 'Combustible', 1, 'Demoras causadas por disponibilidad o gestión de combustible.', ARRAY['Vuelo VB7009 de fecha 27/11/2025'], 'Demora de 23 minutos por falta de personal.'),
(2025, 'Noviembre', 'Autoridad', 0, 'Demoras relacionadas con inspecciones o procesos a cargo de la autoridad.', ARRAY[]::TEXT[], ''),
(2025, 'Noviembre', 'Meteorología', 12, 'Sucede por esperar mejores condiciones meteorológicas en el aeropuerto de destino, principalmente lluvia y bancos de niebla.', ARRAY[]::TEXT[], ''),
(2025, 'Noviembre', 'Aeropuerto', 1, 'Demoras derivadas de infraestructura o servicios del propio aeropuerto.', ARRAY['Vuelo VB9496 de fecha 17/11/2025'], 'Demora de 20 minutos por falla del dispositivo electrónico; que abre y cierra la esclusa electrónicamente (relevador), en la posición 106A.'),
(2025, 'Diciembre', 'Repercusión', 0, 'Se origina en otros aeropuertos y su consecuente llegada tardía al AIFA.', ARRAY[]::TEXT[], ''),
(2025, 'Diciembre', 'Compañía', 0, 'Las principales causas son mantenimiento no programado, espera de tripulación, conveniencia de la aerolínea y flujo lento de pasajeros.', ARRAY[]::TEXT[], ''),
(2025, 'Diciembre', 'Evento Circunstancial', 0, 'Se origina por pasajeros disruptivos, pasajeros o tripulantes enfermos, pasajeros con poca movilidad, así como, espera por tráfico aéreo.', ARRAY[]::TEXT[], ''),
(2025, 'Diciembre', 'Combustible', 0, 'Demoras causadas por disponibilidad o gestión de combustible.', ARRAY[]::TEXT[], ''),
(2025, 'Diciembre', 'Autoridad', 0, 'Demoras relacionadas con inspecciones o procesos a cargo de la autoridad.', ARRAY[]::TEXT[], ''),
(2025, 'Diciembre', 'Meteorología', 0, 'Sucede por esperar mejores condiciones meteorológicas en el aeropuerto de destino, principalmente lluvia y bancos de niebla.', ARRAY[]::TEXT[], ''),
(2025, 'Diciembre', 'Aeropuerto', 0, 'Demoras derivadas de infraestructura o servicios del propio aeropuerto.', ARRAY[]::TEXT[], '');