-- Enable Row Level Security
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- 1. Operations Summary (Replaces staticData)
create table if not exists operations_summary (
  id bigint generated by default as identity primary key,
  year integer not null,
  month integer, -- null for yearly totals
  category text not null, -- 'comercial', 'carga', 'general'
  metric text not null, -- 'operaciones', 'pasajeros', 'toneladas'
  value numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Medical Attentions (Replaces atenciones_medicas.json)
create table if not exists medical_attentions (
  id bigint generated by default as identity primary key,
  year integer not null,
  month text not null, -- 'ENERO', 'FEBRERO', etc.
  aifa_count integer default 0,
  other_company_count integer default 0,
  passenger_count integer default 0,
  visitor_count integer default 0,
  total integer generated always as (aifa_count + other_company_count + passenger_count + visitor_count) stored,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Wildlife Incidents (Replaces fauna.json)
create table if not exists wildlife_incidents (
  id bigint generated by default as identity primary key,
  date date,
  time time,
  location text,
  impact_zone text,
  phase text,
  airline text,
  aircraft text,
  registration text,
  remains_location text,
  remains_amount text,
  size text,
  species text,
  common_name text,
  reporter text,
  proactive_measures text,
  weather_conditions text,
  results text,
  observations text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Flight Itinerary (Replaces itinerario.json)
create table if not exists flight_itinerary (
  id bigint generated by default as identity primary key,
  category text, -- 'Pasajeros', 'Carga'
  airline text,
  aircraft text,
  arrival_flight text,
  arrival_date date,
  arrival_time time,
  origin text,
  claim_belt text,
  position text,
  departure_flight text,
  departure_date date,
  departure_time time,
  destination text,
  gate text,
  status text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Delays (Replaces demoras.json)
create table if not exists delays (
  id bigint generated by default as identity primary key,
  year integer not null,
  month text not null,
  cause text not null, -- 'Repercusión', 'Compañía', etc.
  count integer default 0,
  description text,
  observations text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Punctuality (Replaces puntualidad.json)
create table if not exists punctuality (
  id bigint generated by default as identity primary key,
  year integer not null,
  month text not null,
  category text,
  airline text,
  on_time integer default 0,
  delayed integer default 0,
  cancelled integer default 0,
  total integer generated always as (on_time + delayed + cancelled) stored,
  percentage numeric, -- Can be calculated, but storing for cache
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies (Example: Allow read to everyone, write to authenticated users with role)
-- For now, we'll allow public read and authenticated write.

alter table operations_summary enable row level security;
create policy "Public read access" on operations_summary for select using (true);
create policy "Authenticated update access" on operations_summary for all using (auth.role() = 'authenticated');

alter table medical_attentions enable row level security;
create policy "Public read access" on medical_attentions for select using (true);
create policy "Authenticated update access" on medical_attentions for all using (auth.role() = 'authenticated');

alter table wildlife_incidents enable row level security;
create policy "Public read access" on wildlife_incidents for select using (true);
create policy "Authenticated update access" on wildlife_incidents for all using (auth.role() = 'authenticated');

alter table flight_itinerary enable row level security;
create policy "Public read access" on flight_itinerary for select using (true);
create policy "Authenticated update access" on flight_itinerary for all using (auth.role() = 'authenticated');

alter table delays enable row level security;
create policy "Public read access" on delays for select using (true);
create policy "Authenticated update access" on delays for all using (auth.role() = 'authenticated');

alter table punctuality enable row level security;
create policy "Public read access" on punctuality for select using (true);
create policy "Authenticated update access" on punctuality for all using (auth.role() = 'authenticated');
