
-- Medical History Table
create table if not exists medical_history (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id text,
  action text not null, -- 'CREATE', 'UPDATE', 'DELETE'
  old_data jsonb,
  new_data jsonb,
  changed_by text,
  changed_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table medical_history enable row level security;

create policy "Enable read for admin and medical" on medical_history
  for select using (
    exists (
      select 1 from user_roles
      where user_id = auth.uid()
      and role in ('admin', 'superadmin', 'servicio_medico')
    )
  );

create policy "Enable insert for admin and medical" on medical_history
  for insert with check (
    exists (
      select 1 from user_roles
      where user_id = auth.uid()
      and role in ('admin', 'superadmin', 'servicio_medico')
    )
  );
