-- Tabla diseñada para recibir los datos del PDF "Parte de Operaciones"
-- Se estructura para guardar cada operación (Llegada o Salida) individualmente
-- para facilitar ordenamiento cronológico y gráficas.

CREATE TABLE IF NOT EXISTS public.daily_flights_ops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    
    -- Campos comunes
    aerolinea TEXT,
    matricula TEXT,
    
    -- Detalles de la operación
    tipo_operacion TEXT CHECK (tipo_operacion IN ('Llegada', 'Salida')),
    vuelo TEXT,                 -- Vuelo llegada o Vuelo salida
    origen_destino TEXT,        -- Origen o Destino
    
    -- Horarios
    hora_programada TEXT,       -- "Hora programada" del PDF
    hora_real TEXT,             -- "Hora de salida" (Real) del PDF
    
    -- Métricas
    pasajeros INTEGER,
    
    estatus TEXT DEFAULT 'Programado',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Políticas de seguridad
ALTER TABLE public.daily_flights_ops ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read access" ON public.daily_flights_ops FOR SELECT USING (true);
CREATE POLICY "Authenticated full access" ON public.daily_flights_ops FOR ALL USING (auth.role() = 'authenticated');

-- Índice
CREATE INDEX IF NOT EXISTS idx_daily_flights_ops_fecha ON public.daily_flights_ops(fecha);
