-- Create flights table for itinerary
CREATE TABLE IF NOT EXISTS flights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_llegada DATE,
    hora_llegada TIME,
    vuelo_llegada TEXT,
    origen TEXT,
    aerolinea TEXT,
    equipo TEXT,
    imagen TEXT,
    fecha_salida DATE,
    hora_salida TIME,
    vuelo_salida TEXT,
    destino TEXT,
    posicion TEXT,
    banda_reclamo TEXT,
    categoria TEXT,
    estatus TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add index on dates for faster querying
CREATE INDEX IF NOT EXISTS idx_flights_fecha_llegada ON flights(fecha_llegada);
CREATE INDEX IF NOT EXISTS idx_flights_fecha_salida ON flights(fecha_salida);

-- Enable RLS
ALTER TABLE flights ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all access (since this is an internal tool for now, or adjust as needed)
CREATE POLICY "Enable read access for all users" ON flights FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON flights FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON flights FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON flights FOR DELETE USING (true);
