-- Create wildlife_strikes table if it doesn't exist
create table if not exists public.wildlife_strikes (
  id bigint generated by default as identity primary key,
  date date,
  time time,
  location text,
  impact_zone text,
  operation_phase text,
  airline text,
  aircraft text,
  registration text,
  impact_zone_remains text,
  remains_count integer default 0,
  size text,
  species text,
  common_name text,
  reporter text,
  proactive_measures text,
  weather_conditions text,
  measure_results text,
  observations text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for wildlife_strikes
alter table public.wildlife_strikes enable row level security;

create policy "Enable read access for all users" on public.wildlife_strikes
  for select using (true);

create policy "Enable insert for authenticated users only" on public.wildlife_strikes
  for insert with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" on public.wildlife_strikes
  for update using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only" on public.wildlife_strikes
  for delete using (auth.role() = 'authenticated');


-- Create rescued_wildlife table if it doesn't exist
create table if not exists public.rescued_wildlife (
  id bigint generated by default as identity primary key,
  date date,
  time time,
  capture_number integer,
  class text,
  common_name text,
  scientific_name text,
  quantity integer default 1,
  capture_method text,
  quadrant text,
  final_disposition text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for rescued_wildlife
alter table public.rescued_wildlife enable row level security;

create policy "Enable read access for all users" on public.rescued_wildlife
  for select using (true);

create policy "Enable insert for authenticated users only" on public.rescued_wildlife
  for insert with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" on public.rescued_wildlife
  for update using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only" on public.rescued_wildlife
  for delete using (auth.role() = 'authenticated');
