-- Script generado para poblar catálogos desde CSVs (Airlines.csv y Airports.csv)

-- 1. Catálogo de Aerolíneas
CREATE TABLE IF NOT EXISTS catalogo_aerolineas (codigo_iata TEXT PRIMARY KEY, nombre_aerolinea TEXT);
ALTER TABLE catalogo_aerolineas ADD COLUMN IF NOT EXISTS logo TEXT;
ALTER TABLE catalogo_aerolineas ADD COLUMN IF NOT EXISTS color TEXT;

INSERT INTO catalogo_aerolineas (codigo_iata, nombre_aerolinea) VALUES
('YQ', 'TAR'),
('DM', 'Arajet'),
('GB', 'ABX Air'),
('CX', 'Cathay Pacific'),
('PQ', 'Personas Y Paquetes Por Air'),
('RE', 'Aeroregional'),
('5D', 'Aeromexico Connect'),
('FX', 'FEDEX'),
('VB', 'Viva'),
('V0', 'Conviasa'),
('CA', 'Air China'),
('LZ', 'Legend Airways LLC'),
('ZV', 'Aerus'),
('CI', 'China Airlines'),
('OK', 'Czech Airlines'),
('JU', 'USA Jet Airlines'),
('YA', 'Berry Aviation'),
('GA', 'Garuda Indonesia'),
('A8', 'Ameriflight'),
('U7', 'Uniworld Air Cargo'),
('Y8', 'Suparna Airlines'),
('LX', 'Swiss International Air Lines'),
('MI', 'Taxi Aéreo Monterrey'),
('TE', 'Sky Taxi'),
('NZ', 'Air New Zealand'),
('2D', 'Eastern Airlines'),
('AU', 'Canada Jetlines'),
('G3', 'City Connexion Airlines'),
('GH', 'Galistair Trading Limited'),
('1A', 'FBONLU'),
('LY', 'El Al Israel Airlines'),
('6R', 'Aerotransporte de Carga Unión'),
('Q6', 'Volaris CostaRica'),
('TP', 'TAP Portugal'),
('N3', 'Volaris ElSalvador'),
('MD', 'McNeely Charter Services'),
('OS', 'Austrian Airlines'),
('EU', 'Eurus Aviation'),
('QF', 'Qantas Airways'),
('VS', 'Virgin Atlantic'),
('AR', 'Aerolíneas Argentinas'),
('G2', 'GullivAir'),
('KE', 'Korean Air'),
('YO', 'TAR AEROLINEAS.'),
('6N', 'AEROSUCRE S.A'),
('SU', 'Aeroflot Russian Airlines'),
('VZ', 'Air Class Líneas Aéreas'),
('WT', 'SWIFT AIR LLC'),
('E9', 'Iberojet'),
('WH', 'La Nueva Aerolínea'),
('W2', 'World to Fly'),
('AY', 'Finnair'),
('UJ', 'MAGNICHARTERS'),
('UC', 'Lan Cargo S.A.'),
('SK', 'Scandinavian Airlines'),
('SM', 'TSM Airline'),
('JL', 'Japan Airlines'),
('AD', 'Linea Aerea Azul'),
('UX', 'Air Europa'),
('N8', 'National Airlines Cargo'),
('SY', 'Sun Country Airlines'),
('G6', 'Global Crossing'),
('W8', 'Cargojet Airways'),
('Y4', 'Volaris'),
('VH', 'Aeropostal Alas de Venezuela'),
('VW', 'Aeromar'),
('TN', 'Air Tahiti Nui'),
('UA', 'United Airlines'),
('IF', 'IFL Group'),
('5V', 'Everts Air'),
('BA', 'British Airways'),
('FP', 'Fly Pro'),
('TK', 'Turkish Airlines'),
('CM', 'Copa Airlines'),
('PU', 'Plus Ultra'),
('AM', 'Aeromexico'),
('KD', 'Western Global Airlines'),
('AV', 'Avianca'),
('XL', 'LATAM Ecuador'),
('QR', 'Qatar Airways'),
('E7', 'Estafeta'),
('L3', 'DHL Guatemala'),
('ZT', 'Titan Airways'),
('NH', 'All Nippon Airways'),
('M3', 'ABSA'),
('WS', 'WestJet'),
('CV', 'Cargolux'),
('GN', 'General aviation'),
('AF', 'Air France'),
('XN', 'Mexicana'),
('M6', 'Amerijet International'),
('7L', 'Silk Way West Airlines'),
('M7', 'MasAir'),
('GG', 'Sky Lease Cargo'),
('AA', 'American Airlines'),
('A7', 'Awesome Cargo'),
('AC', 'Air Canada'),
('XR', 'CORENDON AIRLINES EUROPE'),
('K9', 'KALITTA CHARTERS II, LLC.'),
('5X', 'United Parcel Service'),
('5Y', 'Atlas Air'),
('LH', 'Lufthansa'),
('KL', 'KLM Airways'),
('LA', 'LATAM Chile'),
('IB', 'Iberia Airlines'),
('SV', 'Saudi Arabian Airlines Cargo'),
('K4', 'Kalitta Air'),
('L7', 'LATAM Cargo Colombia'),
('L2', 'Lynden Air Cargo'),
('G4', 'Allegiant Air LLC'),
('ET', 'Ethiopian Airlines'),
('FV', 'Pulkovo Aviation Enterprise'),
('5R', 'Rutaca Airlines'),
('DL', 'Delta Air Lines'),
('OY', 'Omni Air International'),
('EK', 'Emirates Airlines'),
('CZ', 'China Southerrn')
ON CONFLICT (codigo_iata) DO UPDATE SET nombre_aerolinea = EXCLUDED.nombre_aerolinea;
;

-- 2. Catálogo de Aeropuertos
CREATE TABLE IF NOT EXISTS catalogo_aeropuertos (iata TEXT PRIMARY KEY, ciudad TEXT);
ALTER TABLE catalogo_aeropuertos ADD COLUMN IF NOT EXISTS pais TEXT DEFAULT 'México';
ALTER TABLE catalogo_aeropuertos ADD COLUMN IF NOT EXISTS estado TEXT;
ALTER TABLE catalogo_aeropuertos ADD COLUMN IF NOT EXISTS nombre_aeropuerto TEXT;

INSERT INTO catalogo_aeropuertos (iata, ciudad, pais, nombre_aeropuerto) VALUES
('RIV', 'Riverside', 'United States', 'March Air Reserve Base'),
('PVG', 'Shanghai', 'China', 'Shanghai Pudong International Airport'),
('NAP', 'Naples', 'Italy', 'Naples Capodichino'),
('CLO', 'Cali', 'Colombia', 'Alfonso Bonilla Aragón International Airport'),
('CLQ', 'Colima', 'Mexico', 'Licenciado Miguel de la Madrid Airport'),
('JJC', 'Atizapan de Zaragoza', 'Mexico', 'DR JORGE JIMENEZ CANTU'),
('GDL', 'Guadalajara', 'Mexico', 'Guadalajara Miguel Hidalgo Y Costilla Int&#39;l'),
('NRT', 'Tokyo', 'Japan', 'Narita International'),
('BJX', 'Bajio', 'Mexico', 'El Bajio'),
('SLC', 'Salt Lake City', 'United States', 'Salt Lake City International'),
('CLT', 'Charlotte', 'United States', 'Charlotte Douglas International'),
('PVR', 'Puerto Vallarta', 'Mexico', 'Licenciado Gustavo Ordaz'),
('SLP', 'San Luis Potosi', 'Mexico', 'Ponciano Arriaga International'),
('DOC', 'Dornoch', 'United Kingdom', 'Dornoch Airfield'),
('UPN', 'Uruapan', 'Mexico', 'Uruapan International Airport'),
('GUA', 'Guatemala City', 'Guatemala', 'La Aurora International'),
('FBO', '', '', 'FBO NLU'),
('CMH', 'Columbus', 'United States', 'John Glenn Columbus International Airport'),
('SLW', 'Saltillo', 'Mexico', 'Aeropuerto Internacional de Saltillo'),
('YHM', 'Hamilton', 'United States', 'Hamilton International Airport'),
('CME', 'Ciudad Del Carmen', 'Mexico', 'Ciudad Del Carmen Int&#39;l'),
('DOH', 'Hamad', 'Qatar', 'Hamad International Airport'),
('AZA', 'Phoenix', 'United States', 'Phoenix–Mesa Gateway Airport'),
('VSA', 'Villahermosa', 'Mexico', 'Carlos Rovirosa Perez Int&#39;l'),
('CMN', 'Casablanca', 'Morocco', 'Aeropuerto Internacional Mohammed V'),
('MAD', 'Madrid', 'Spain', 'Adolfo Suarez Madrid Barajas Int&#39;l'),
('DOV', 'Dover', 'United Kingdom', 'Dover AFB Airport'),
('YHZ', 'Halifax', 'Canada', 'Halifax'),
('SMF', 'Sacramento', 'United States', 'Sacramento Int&#39;l'),
('BLB', 'Panama, Ciudad de', 'Panama', 'Panamá Pacífico International Airport'),
('MAM', 'Matamoros', 'Mexico', 'General Servando Canales Int&#39;l'),
('HGR', 'Washington', 'United States', 'Hagerstown Regional Airport'),
('YYT', '', '', 'St. Jhon´s International Airport'),
('ORB', 'Örebro', 'Sweden', 'Örebro Airport'),
('GRK', 'Texas', 'United States', 'Robert Gray Army Airfield'),
('ORD', 'Chicago', 'United States', 'OHare Internationa'),
('OAX', 'Oaxaca', 'Mexico', 'Xoxocotlan International'),
('FPO', '', '', 'Freeport Grand Bahama International Airport'),
('GRU', 'Sao Paulo', 'Brazil', 'Sao Paulo Guarulhos'),
('TLC', 'Toluca', 'Mexico', 'A.I. Lic. Adolfo López Mateos'),
('SJC', 'San Jose', 'United States', 'San Jose California International'),
('CJS', 'Ciudad Juarez', 'Mexico', 'Abraham Gonzalez Int&#39;l'),
('SJD', 'San Jose Del Cabo', 'Mexico', 'Los Cabos International'),
('WAW', 'Warsaw', 'Poland', 'Warsaw Chopin Airport'),
('SJO', 'San Jose', 'United States', 'Juan Santamaria International'),
('AFW', '', 'United States', 'Perot Field Fort Worth Alliance Airport'),
('SZY', '', 'Poland', 'Olsztyn-Mazury Airport'),
('PTY', 'Panama City', 'Panama', 'Tocumen International'),
('YVR', 'Vancouver', 'Canada', 'Vancouver Int&#39;l'),
('SJU', 'San Juan', 'Puerto Rico', 'Luis Muñoz Marín International Airport'),
('PDS', 'Piedras Negras', 'Mexico', 'Piedras Negras International'),
('BIF', 'Texas', 'United States', 'Biggs Army Airfield'),
('OSL', 'Oslo', 'Norway', 'Oslo-Gardermoen, Oslo, Nor.'),
('YWG', 'Winnipeg Manitoba', 'Canada', 'Aeropuerto Internacional de Winnipeg'),
('GSO', 'Carolina', 'Brazil', 'Piedmont Triad International Airport'),
('PDX', 'Portland', 'United States', 'Portland International Airport'),
('GSP', 'Greenville', 'United States', 'Aeropuerto Internacional Greenville'),
('PUJ', 'Punta Cana', 'Dominican Republic', 'Punta Cana International Airport'),
('FAI', '', 'United States', 'Fairbanks International Airport'),
('AGU', 'Aguascalientes', 'Mexico', 'Lic. Jesus Teran Aguascalientes'),
('OST', 'Oostende Brugge', 'Belgium', 'Ostend Bruges International'),
('TMC', '', '', 'Tambolaka Airport'),
('HUX', 'Huatulco', 'Mexico', 'Bahias de Huatulco Int&#39;l'),
('LMM', 'Los Mochis', 'Mexico', 'AEROPUERTO FEDERAL DEL VALLE DEL FUERTE'),
('FAT', 'Fresno', 'United States', 'Frezno Yosemite International'),
('ZIH', 'Ixtapa Zihuatanejo', 'Mexico', 'Ixtapa Zihuatanejo International'),
('FRA', 'Frankfurt', 'Germany', 'Frankfurt'),
('PAP', '', 'Haiti', 'Toussaint Louverture Aeropuerto Internacional'),
('PAM', '', 'United States', 'Tyndall Air Force Base'),
('HAV', 'La Habana', 'Cuba', 'Jose Marti Internationa'),
('PAZ', '', '', 'Poza Rica'),
('ELP', 'Texas', 'United States', 'El Paso International Airport'),
('BFM', '', 'United States', 'Mobile International Airpor'),
('HRL', 'Harlingen', 'United States', 'Valley International Airport'),
('BFI', 'Seattle', 'United States', 'Boeing Field, King County'),
('REX', 'Reynosa', 'Mexico', 'General Lucio Blanco'),
('MLM', 'Morelia', 'Mexico', 'General Francisco J. Mujica International Airport'),
('CHS', '', '', 'Charlestone International Airport'),
('JFK', 'New York', 'United States', 'John F. Kennerdy International'),
('PBC', 'Puebla', 'Mexico', 'Hermanos Serdán International Airport'),
('GPT', 'Harrison', 'United States', 'Gulfport-Biloxi Internacional Airport'),
('KHV', 'Khabarovsk', 'Russian Federation', 'khabarovsk Novy Airport'),
('ADW', 'Camp Springs', 'United States', 'Joint Base Andrews Airport'),
('BWI', 'Washington-Baltimore Int Apt', 'United States', 'Thurgood Marshall Airport'),
('AUS', 'Austin', 'United States', 'Austin-Bergstrom Int&#39;l'),
('CYW', 'Celaya', 'Mexico', 'Aeropuerto de Celaya'),
('SHV', 'Louisiana', 'United States', 'Shreveport Regional Airport'),
('PBM', 'Paramaribo', 'Suriname', 'Aeropuerto Internacional Adolf Pengel'),
('BGI', 'Christchurch', 'New Zealand', 'Grantley Adams International Airport'),
('SID', 'Sal Island', 'Cape Verde', 'Amilcar Cabral International'),
('PCA', 'Portage Creek', 'United States', 'Portage Creek Airport'),
('YUL', 'Montreal', 'Canada', 'Montreal Trudeau International'),
('KIN', 'Kingston', 'Jamaica', 'Norman Manley'),
('HSV', 'Huntsville', 'United States', 'Huntsville International Airport'),
('CZM', 'Cozumel', 'Mexico', 'Cozumel International'),
('OAK', 'Oakland', 'United States', 'Oakland International'),
('AEX', 'Louisiana', 'United States', 'Alexandria International Airport'),
('YQX', 'Gander', 'Canada', 'Gander International'),
('CVM', 'Ciudad Victoria', 'Mexico', 'General Pedro J.Mendez'),
('UIO', 'Quito', 'Ecuador', 'Mariscal Sucre International'),
('NLD', 'Nuevo Laredo', 'Mexico', 'Quetzalcoatl International'),
('FLL', 'Fort Lauderdale', 'United States', 'International Airport Fort Lauderdale'),
('TGZ', 'Tuxtla Gutierrez', 'Mexico', 'Aeropuerto Internacional Angel Albino Corzo'),
('MZT', 'Mazatlan', 'Mexico', 'General Rafael Buelna'),
('ZCL', 'Zacatecas', 'Mexico', 'General Leobardo C.Ruiz Int&#39;l'),
('QRO', 'Queretaro', 'Mexico', 'Querétaro International'),
('CWB', 'Curitiba', 'Brazil', 'Afonso Pena International Airport'),
('BUD', 'Budapest', 'Hungary', 'Budapest Int. Airport'),
('LHR', 'London', 'United Kingdom', 'Heathrow Airport'),
('NLU', 'Mexico City', 'Mexico', 'Aeropuerto Internacional Felipe Ángeles'),
('CWF', 'Louisiana', 'United States', 'Chennault International Airport'),
('ONT', 'Ontario', 'United States', 'Ontario international'),
('ACA', 'Acapulco', 'Mexico', 'General Juan N.Alvarez Int&#39;l'),
('SFO', 'San Francisco', 'United States', 'San Francisco International'),
('TYN', 'Taiyuan', 'China', 'Taiyuan Wusu International Airport'),
('LIM', 'Lima', 'Peru', 'Jorge Chavez International'),
('REC', 'Recife', 'Brazil', 'Aeropuerto de Recife'),
('IST', 'Istanbul', 'Turkey', 'Istanbul New Airport'),
('ICD', '', 'Mexico', 'AEROPUERTO NACIONAL DE ISLA DE CEDROS'),
('CGO', 'Zhengzhou', 'China', 'Zhengzhou Xinzheng International Airport'),
('PQM', 'Palenque', 'Mexico', 'Aeropuerto Int. Palenque'),
('LIS', '', '', 'Humberto Delgado, Lisboa, Portugal'),
('CXL', 'Calexico', 'United States', 'Aeropuerto Internacional de Calexico'),
('HRB', 'Harbin', 'China', 'Harbin Taiping International'),
('ATL', 'Atlanta', 'United States', 'Hartsfield Jackson Atlanta Intl'),
('ICN', 'Incheon Intl Apt/Seoul', 'Korea, Republic of', 'Incheon International'),
('TIJ', 'Tijuana', 'Mexico', 'Tijuana'),
('LIR', 'Liberia', 'Costa Rica', 'Guanacaste'),
('ATH', 'Athens', 'Greece', 'Athens Airport'),
('BRO', 'Condado de Cameron', 'United States', 'Airport International Brownsville'),
('MXL', 'Mexicali', 'Mexico', 'General Rodolfo Sanchez Taboada'),
('SCL', 'Santiago', 'Chile', 'Comodoro Arturo Merino Benitez Int&#39;l'),
('CTM', 'Chetumal', 'Mexico', 'Chetumal International'),
('CDG', 'Paris', 'France', 'Charles De gaulle Airport'),
('HNL', 'Honolulu', 'United States', 'Inouye International Airport'),
('CTS', 'Sapporo', 'Japan', 'New Chitose Airport'),
('BRU', 'Brussels', 'Belgium', 'Brussels Airport'),
('MXP', 'Milan', 'Italy', 'Milan Malpensa Airport'),
('DWC', 'Dubai', 'United Arab Emirates', 'Aeropuerto Internacional de Dubai-Al Maktoum'),
('NZY', 'San Diego', 'United States', 'San Diego North Island Naval Air Station'),
('ZAZ', 'Zaragoza', 'Spain', 'Zaragoza Airport'),
('SDF', 'Louisville', 'United States', 'Louisville International'),
('DFW', 'Dallas Fort Worth', 'United States', 'Dallas Fort Worth International'),
('SDQ', 'Santo Domingo', 'Dominican Republic', 'Las Americas International'),
('CUL', 'Culiacan', 'Mexico', 'Bachigualato federal Inernational'),
('CUN', 'Cancún', 'Mexico', 'Cancún'),
('MID', 'Merida', 'Venezuela, Bolivarian Republic of', 'Manuel Crecencio Rejon'),
('CED', 'Zacatecas', 'Mexico', 'Aeródromo de Cedros'),
('CUU', 'Chihuahua', 'Mexico', 'General Roberto Fierro Villalobos'),
('MIA', 'Miami', 'United States', 'Miami International Airport'),
('HOU', 'Houston', 'United States', 'Willian P Hobby'),
('DXB', 'Dubai', 'United Arab Emirates', 'Aeropuerto Internacional de Dubai'),
('SEA', 'Seattle', 'United States', 'Seattle - Tacoma International'),
('IAH', 'Houston', 'United States', 'George Bush'),
('EZE', 'Buenos Aires', 'Argentina', 'Ministro Pistarini'),
('LGG', 'Liege', 'Belgium', 'Liege Airport'),
('KEF', 'Reykjavik', 'Iceland', 'Keflavik International'),
('DGO', 'Durango', 'Mexico', 'General Guadalupe Victoria Int&#39;l'),
('IAD', 'Washington', 'United States', 'Washington Dulles International'),
('CEN', 'Ciudad Obregon', 'Mexico', 'Ciudad Obregon International'),
('BCN', 'Barcelona', 'Spain', 'Barcelona el Prat Airport'),
('YQK', 'Kenora', 'Canada', 'Kenora Airport Authority Inc.'),
('CVG', 'Cincinnati', 'United States', 'Cincinati'),
('POS', '', 'Trinidad and Tobago', 'Aeropuerto Internacional de Piarco'),
('SAL', 'San Salvador', 'El Salvador', 'Monsenor Oscar Arnulfo Romero'),
('TCM', 'Los Angeles', 'United States', 'McChord Field Airport'),
('IND', 'Indianapolis', 'United States', 'Indianapolis'),
('MEX', 'Mexico City', 'Mexico', 'Aeropuerto Internacional Benito Juárez'),
('SAN', 'San Diego', 'United States', 'San Diego'),
('WRI', 'Washington', 'United States', 'McGuire Air Force Base'),
('MVD', 'Montevideo', 'United States', 'Aeropuerto Internacional de Carrasco'),
('SAT', 'San Antonio', 'United States', 'San Antonia International'),
('LTO', 'Loreto', 'Mexico', 'Loreto International Airport'),
('DTW', 'Detroit', 'United States', 'Detroit Metropolitan Wayne County Airport'),
('SAP', 'San Pedro Sula', 'Honduras', 'Ramon Villeda Morales'),
('YMX', 'Mirabel Apt/Montreal', 'Canada', 'Montréal International Airport'),
('MFE', 'McAllen Mission', 'United States', 'McAllen Miller Int&#39;l'),
('SBD', '', 'United States', 'SAN BERNARDINO INTERNATIONAL AIRPORT'),
('EWR', 'Newark', 'United States', 'Newark Liberty Int&#39;l'),
('MGA', 'Managua', 'Nicaragua', 'Agusto C. Sandino International'),
('LUK', 'Cincinnati', 'United States', 'Cincinnati Municipal Airport'),
('LUX', 'Luxembourg', 'Luxembourg', 'Luxembourg Findel Airport'),
('HMO', 'Hermosillo', 'Mexico', 'General Ignacio Pesqueria Garcia'),
('DEN', 'Denver', 'United States', 'Denver International'),
('TUS', '', '', 'Tucson International Airport'),
('BAQ', '', '', 'Barranquilla Ernesto Cortissoz International Airport'),
('CCS', 'Caracas', 'Venezuela', 'Caracas Airport'),
('LAS', 'Las Vegas', 'United States', 'McCarran International'),
('LRD', 'Laredo', 'United States', 'Laredo International'),
('TAM', 'Tampico', 'Mexico', 'General Francisco Javier Mina Int&#39;l'),
('LAP', 'La Paz', 'Mexico', 'Manuel Marquez DeLeon'),
('PIT', '', 'United States', 'Aeropuerto Internacional de Pittsburgh'),
('LRM', 'La Romana', 'Dominican Republic', 'Aeropuerto Internacional de La Romana'),
('EDF', 'Anchorage', 'United States', 'Elmendorf Air Force Base'),
('LAX', 'Los Angeles', 'United States', 'Los Angeles International Airport'),
('TAP', 'Tapachula', 'Mexico', 'Tapachula International'),
('VER', 'Veracruz', 'Mexico', 'General Heriberto Jara Int&#39;l'),
('TRC', 'Torreon', 'Mexico', 'FRANCISCO SARABIA, TORREON INT&#39;L'),
('DRS', 'Dresden', 'Germany', 'Dresden Airport'),
('MDE', 'Medellin', 'Colombia', 'Jose Maria Cordova Int&#39;l'),
('MTT', 'Minatitlan', 'Mexico', 'Minatitlan Coatzacoalcos Int&#39;l'),
('MTY', 'Monterrey', 'Mexico', 'General Mariano Escobedo Int&#39;l'),
('RNO', 'Reno', 'United States', 'Reno/Tahoe International Airport'),
('GYE', 'Guayaquil', 'Ecuador', 'Aeropuerto Internacional José Joaquín de Olmedo'),
('LSE', 'Wisconsin Rapids', 'United States', 'La Crosse Regional Airport'),
('MDW', 'Chicago', 'United States', 'Chicago Midway International Airport'),
('GYR', '', 'United States', 'Phoenix Goodyear Airport'),
('BOG', 'Bogota', 'Colombia', 'El Dorado International'),
('MUC', 'Munich', 'Germany', 'Munich Airport'),
('AMS', 'Amsterdam', 'Netherlands', 'Amsterdam Airport Schiphol'),
('DSV', 'Dansville', 'United States', 'Dansville'),
('HKG', 'Hong Kong', 'Hong Kong', 'Hong Kong'),
('GIG', 'Rio de Janeiro', 'Brazil', 'Rio de Janeiro Galeao International Airport'),
('CAN', 'Canton Baiyun', 'China', 'Aeropuerto Internacional Cantón Baiyun'),
('NGO', 'Nagoya', 'Japan', 'Chubu centrair International'),
('ANC', 'Anchorage', 'United States', 'Ted Stevens Anchorage International'),
('MEM', 'Memphis', 'United States', 'Memphis International Airport'),
('MAR', 'Maracay', 'Venezuela, Bolivarian Republic of', 'La Chinita Inernational Airport'),
('UAM', 'Guam', 'Guam', 'Andersen Air Force Base'),
('YYZ', 'Toronto', 'Canada', 'Toronto Pearson Int&#39;l'),
('MAO', 'Manaus', 'Brazil', 'Aeropuerto Internacional de Manaus'),
('VCV', 'San Bernardino', 'United States', 'Southern California Logistics Airport'),
('IZT', 'Ixtepec', 'Mexico', 'Ixtepec Airport'),
('VCP', 'Campinas', 'Brazil', 'Aeropuerto Internacional de Viracopos'),
('PXM', 'Puerto Escondido', 'Mexico', 'Puerto Escondido International'),
('HYI', 'Austin', 'United States', 'San Marcos Regional Airport'),
('SNN', 'Limerick', 'Ireland', 'Shannon Airport'),
('TPQ', 'Tepic', 'Mexico', 'Amdo Nervo Int&#39;l'),
('VDL', 'Atlanta', 'United States', 'Valdosta Regional Airport'),
('PHX', 'Phoenix', 'United States', 'Phoenix Sky Harbor Int&#39;l'),
('ZLO', 'Manzanillo', 'Mexico', 'Playa de Oro'),
('COS', 'Colorado Springs', 'United States', 'Colorado Springs Municipal'),
('MSJ', 'Misawa', 'Japan', 'MISAWA JAPON'),
('HIF', 'Ogden', 'United States', 'HILL AIR FORCE BASE'),
('MSP', 'Minneapolis', 'United States', 'Minneapolis Saint Paul Int&#39;l'),
('HIK', 'Honolulu', 'United States', 'Hickam AFB Airport'),
('SOF', '', 'Bulgaria', 'Sofia Airport'),
('CPE', 'Campeche', 'Mexico', 'Alberto Acuna Ongay'),
('MCO', 'Orlando', 'United States', 'Orlando Int&#39;l'),
('ECP', '', '', 'Panama City International Airport'),
('TQO', 'Tulum', 'Mexico', 'FELIPE CARRILLO PUERTO'),
('MCI', 'Kansas City', 'United States', 'Kansas City International Airport'),
('MSY', 'New Orleans', 'United States', 'New Orleans Louis Armstrong International Airport'),
('MKC', 'Kansas City', 'United States', 'Aeropuerto Urbano Charles B. Wheeler'),
('SUU', 'Fairfield', 'United States', 'Travis AFB')
ON CONFLICT (iata) DO UPDATE SET ciudad = EXCLUDED.ciudad, pais = EXCLUDED.pais, nombre_aeropuerto = EXCLUDED.nombre_aeropuerto;
;
