-- SCRIPT DE RECREACIÓN COMPLETA DE LA TABLA DAILY_FLIGHTS_OPS
-- Ejecuta esto en el Editor SQL de Supabase para reiniciar la tabla con la estructura correcta.

-- 1. Eliminar la tabla existente (Cuidado: Se perderán los datos actuales)
DROP TABLE IF EXISTS public.daily_flights_ops;

-- 2. Crear la tabla con las columnas solicitadas
-- Se diseñó para almacenar filas individuales por operación (Llegada o Salida)
-- manteniendo la capacidad de guardar fechas completas en campos de texto.

CREATE TABLE public.daily_flights_ops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Fecha lógica de la operación (para búsquedas por día)
    fecha DATE, 
    
    -- Información de la Aerolínea y Equipo
    aerolinea TEXT,
    matricula TEXT,
    
    -- Identificación de la Operación
    tipo_operacion TEXT CHECK (tipo_operacion IN ('Llegada', 'Salida')),
    vuelo TEXT,                 -- Número de vuelo
    origen_destino TEXT,        -- Ciudad de Origen o Destino según corresponda
    
    -- Tiempos (Se usa TEXT para permitir formatos como "DD/MM/YYYY HH:MM" o "Pernocta")
    hora_programada TEXT,       
    hora_real TEXT,             
    
    -- Métricas
    pasajeros INTEGER DEFAULT 0,
    
    -- Estado y Observaciones
    estatus TEXT DEFAULT 'Programado', -- Ej: "Operó", "Programado", o el tiempo de demora
    observaciones TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Habilitar seguridad (RLS) para permitir uso desde la aplicación
ALTER TABLE public.daily_flights_ops ENABLE ROW LEVEL SECURITY;

-- 4. Política de acceso total (ajusta según tus necesidades de seguridad)
CREATE POLICY "Permitir todo acceso público" ON public.daily_flights_ops
FOR ALL USING (true) WITH CHECK (true);

-- COMENTARIOS DE USO:
-- La tabla guarda operaciones atómicas. 
-- Una fila del PDF de 13 columnas se guarda como:
--   1 Fila de Tipo 'Llegada' con los datos de la izquierda.
--   1 Fila de Tipo 'Salida' con los datos de la derecha (si existen).
-- Ambas comparten la misma 'matricula' y 'aerolinea'.
