-- RECREACIÓN DE TABLA daily_flights_ops (Estructura Ancha / Wide Format)
-- Basada estrictamente en el formato de 13 columnas del PDF solicitado.

DROP TABLE IF EXISTS public.daily_flights_ops;

CREATE TABLE public.daily_flights_ops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Columna auxiliar para búsquedas rápidas por día
    fecha DATE NOT NULL,
    
    -- Columnas del Reporte PDF
    seq_no INTEGER,                 -- "No."
    aerolinea TEXT,                 -- "Aerolínea"
    
    -- Bloque Llegada
    vuelo_llegada TEXT,             -- "Vuelo de llegada"
    origen TEXT,                    -- "Origen"
    fecha_hora_prog_llegada TEXT,   -- "Hora programada" (Arr) - Guarda "08/01/2026 15:00"
    fecha_hora_real_llegada TEXT,   -- "Hora de llegada" (Arr)
    pasajeros_llegada INTEGER DEFAULT 0, -- "Pasajeros" (Arr)
    
    -- Bloque Salida
    vuelo_salida TEXT,              -- "Vuelo de salida"
    destino TEXT,                   -- "Destino"
    fecha_hora_prog_salida TEXT,    -- "Hora programada" (Dep)
    fecha_hora_real_salida TEXT,    -- "Hora de salida" (Dep)
    pasajeros_salida INTEGER DEFAULT 0,  -- "Pasajeros" (Dep)
    
    matricula TEXT,                 -- "Matrícula"
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar permisos
ALTER TABLE public.daily_flights_ops ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON public.daily_flights_ops FOR ALL USING (true) WITH CHECK (true);
