
-- 1. Eliminar la tabla si existe (para empezar de cero)
DROP TABLE IF EXISTS daily_operations;

-- 2. Crear la tabla nuevamente con la estructura correcta
CREATE TABLE IF NOT EXISTS daily_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL UNIQUE,
    comercial_llegada INTEGER DEFAULT 0,
    comercial_salida INTEGER DEFAULT 0,
    carga_llegada INTEGER DEFAULT 0,
    carga_salida INTEGER DEFAULT 0,
    general_llegada INTEGER DEFAULT 0,
    general_salida INTEGER DEFAULT 0,
    total_general INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Comentarios opcionales
COMMENT ON TABLE daily_operations IS 'Registro diario de operaciones aéreas (llegadas y salidas) por tipo de aviación';

-- 4. Habilitar acceso público (opcional, si tienes problemas de permisos)
ALTER TABLE daily_operations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir lectura publica" ON daily_operations
FOR SELECT USING (true);

CREATE POLICY "Permitir todo a autenticados" ON daily_operations
FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Permitir todo a anonimos (si es necesario)" ON daily_operations
FOR ALL TO anon USING (true) WITH CHECK (true);
