const fs = require('fs');
const path = require('path');

const inputFile = path.join(__dirname, '../data/resumen_parte_operaciones.json');
const outputFile = path.join(__dirname, '../resumen_operaciones_inserts.sql');

try {
    const rawData = fs.readFileSync(inputFile, 'utf8');
    const jsonData = JSON.parse(rawData);
    
    let sql = `CREATE TABLE IF NOT EXISTS daily_operations_breakdown (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    operation_type TEXT NOT NULL,
    arrivals INTEGER DEFAULT 0,
    departures INTEGER DEFAULT 0,
    subtotal INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);\n\n`;

    sql += `INSERT INTO daily_operations_breakdown (date, operation_type, arrivals, departures, subtotal) VALUES\n`;

    const values = [];
    const dates = Object.keys(jsonData.dias).sort();

    dates.forEach(date => {
        const dayData = jsonData.dias[date];
        if (dayData.operaciones && Array.isArray(dayData.operaciones)) {
            dayData.operaciones.forEach(op => {
                // Escape single quotes in operation type just in case
                const type = op.tipo.replace(/'/g, "''");
                const arrivals = op.llegada || 0;
                const departures = op.salida || 0;
                const subtotal = op.subtotal || 0;
                
                values.push(`('${date}', '${type}', ${arrivals}, ${departures}, ${subtotal})`);
            });
        }
    });

    if (values.length > 0) {
        sql += values.join(',\n') + ';';
        fs.writeFileSync(outputFile, sql);
        console.log(`Successfully generated SQL with ${values.length} records at ${outputFile}`);
    } else {
        console.log('No records found to insert.');
    }

} catch (error) {
    console.error('Error processing file:', error);
}
