const fs = require('fs');
const path = require('path');

const jsonPath = path.join(__dirname, '../data/resumen_parte_operaciones.json');
const outputSqlPath = path.join(__dirname, '../db/insert_daily_operations_full.sql');

// Ensure db directory exists
const dbDir = path.dirname(outputSqlPath);
if (!fs.existsSync(dbDir)) {
    fs.mkdirSync(dbDir, { recursive: true });
}

const data = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));

let sqlContent = `
-- Create table for daily operations
CREATE TABLE IF NOT EXISTS daily_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL UNIQUE,
    comercial_llegada INTEGER DEFAULT 0,
    comercial_salida INTEGER DEFAULT 0,
    carga_llegada INTEGER DEFAULT 0,
    carga_salida INTEGER DEFAULT 0,
    general_llegada INTEGER DEFAULT 0,
    general_salida INTEGER DEFAULT 0,
    total_general INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add comments for clarity
COMMENT ON TABLE daily_operations IS 'Registro diario de operaciones aéreas (llegadas y salidas) por tipo de aviación';

INSERT INTO daily_operations (fecha, comercial_llegada, comercial_salida, carga_llegada, carga_salida, general_llegada, general_salida, total_general) VALUES
`;

const valuesList = [];
const sortedDates = Object.keys(data.dias).sort();

sortedDates.forEach(dateStr => {
    const dayData = data.dias[dateStr];
    const ops = dayData.operaciones || [];

    let comArr = 0;
    let comDep = 0;
    let cargoArr = 0;
    let cargoDep = 0;
    let genArr = 0;
    let genDep = 0;

    ops.forEach(op => {
        const tipo = op.tipo;
        const llegada = op.llegada || 0;
        const salida = op.salida || 0;

        if (tipo === 'Aviación de Pasajeros') {
            comArr = llegada;
            comDep = salida;
        } else if (tipo === 'Aviación de Carga') {
            cargoArr = llegada;
            cargoDep = salida;
        } else if (tipo === 'Aviación General') {
            genArr = llegada;
            genDep = salida;
        }
    });

    const total = dayData.total_general || 0;
    valuesList.push(`('${dateStr}', ${comArr}, ${comDep}, ${cargoArr}, ${cargoDep}, ${genArr}, ${genDep}, ${total})`);
});

sqlContent += valuesList.join(',\n') + ';';

fs.writeFileSync(outputSqlPath, sqlContent, 'utf8');

console.log(`SQL file generated at: ${outputSqlPath}`);
console.log(`Total records processed: ${valuesList.length}`);
