import json
import os

def generate_sql():
    json_path = r'c:\Users\DO SLOTS\Documents\PROYECTOS\PROYECTOS\AIFA_OPERACIONES\data\resumen_parte_operaciones.json'
    output_sql_path = r'c:\Users\DO SLOTS\Documents\PROYECTOS\PROYECTOS\AIFA_OPERACIONES\db\insert_daily_operations_full.sql'

    # Ensure db directory exists
    os.makedirs(os.path.dirname(output_sql_path), exist_ok=True)

    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    sql_statements = []
    
    # Create table statement
    create_table_sql = """
-- Create table for daily operations
CREATE TABLE IF NOT EXISTS daily_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL UNIQUE,
    comercial_llegada INTEGER DEFAULT 0,
    comercial_salida INTEGER DEFAULT 0,
    carga_llegada INTEGER DEFAULT 0,
    carga_salida INTEGER DEFAULT 0,
    general_llegada INTEGER DEFAULT 0,
    general_salida INTEGER DEFAULT 0,
    total_general INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add comments for clarity
COMMENT ON TABLE daily_operations IS 'Registro diario de operaciones aéreas (llegadas y salidas) por tipo de aviación';
"""
    sql_statements.append(create_table_sql)
    
    sql_statements.append("INSERT INTO daily_operations (fecha, comercial_llegada, comercial_salida, carga_llegada, carga_salida, general_llegada, general_salida, total_general) VALUES")

    values_list = []
    
    # Sort dates to ensure chronological order
    sorted_dates = sorted(data['dias'].keys())

    for date_str in sorted_dates:
        day_data = data['dias'][date_str]
        ops = day_data.get('operaciones', [])
        
        # Initialize counters
        com_arr = 0
        com_dep = 0
        cargo_arr = 0
        cargo_dep = 0
        gen_arr = 0
        gen_dep = 0
        
        for op in ops:
            tipo = op.get('tipo')
            llegada = op.get('llegada', 0)
            salida = op.get('salida', 0)
            
            if tipo == 'Aviación de Pasajeros':
                com_arr = llegada
                com_dep = salida
            elif tipo == 'Aviación de Carga':
                cargo_arr = llegada
                cargo_dep = salida
            elif tipo == 'Aviación General':
                gen_arr = llegada
                gen_dep = salida
        
        total = day_data.get('total_general', 0)
        
        # Format value string
        value_str = f"('{date_str}', {com_arr}, {com_dep}, {cargo_arr}, {cargo_dep}, {gen_arr}, {gen_dep}, {total})"
        values_list.append(value_str)

    # Join all values with commas and add a semicolon at the end
    sql_statements.append(",\n".join(values_list) + ";")

    # Write to file
    with open(output_sql_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(sql_statements))

    print(f"SQL file generated at: {output_sql_path}")
    print(f"Total records processed: {len(values_list)}")

if __name__ == "__main__":
    generate_sql()
