-- Ajustes manuales de Conciliación sobre filas provenientes del Itinerario.
-- No modifica vuelos_parte_operaciones_csv ni afecta la pestaña Itinerario.
create table if not exists public.conciliacion_vuelo_overrides (
  id bigint generated by default as identity primary key,
  vuelo_id bigint not null,
  direccion text not null check (direccion in ('LLEGADA', 'SALIDA')),
  aerolinea text,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id),
  unique (vuelo_id, direccion)
);

create index if not exists idx_conci_vuelo_overrides_lookup
  on public.conciliacion_vuelo_overrides (vuelo_id, direccion);

alter table public.conciliacion_vuelo_overrides enable row level security;

create or replace function public.get_conciliacion_vuelo_airline_overrides()
returns table(vuelo_id bigint, direccion text, aerolinea text)
language sql stable security definer set search_path = public
as $$
  select o.vuelo_id, o.direccion, o.aerolinea
  from public.conciliacion_vuelo_overrides o;
$$;

create or replace function public.save_conciliacion_vuelo_airline_override(
  p_vuelo_id bigint,
  p_direccion text,
  p_aerolinea text
) returns public.conciliacion_vuelo_overrides
language plpgsql security definer set search_path = public
as $$
declare result_row public.conciliacion_vuelo_overrides;
begin
  if not exists (
    select 1 from public.user_roles
    where user_id = auth.uid()
      and lower(role) in ('admin', 'superadmin', 'editor', 'capturista', 'superuser')
  ) then
    raise exception 'El usuario no tiene permiso para editar Conciliación';
  end if;

  insert into public.conciliacion_vuelo_overrides
    (vuelo_id, direccion, aerolinea, updated_by, updated_at)
  values
    (p_vuelo_id, upper(p_direccion), nullif(trim(p_aerolinea), ''), auth.uid(), now())
  on conflict (vuelo_id, direccion) do update set
    aerolinea = excluded.aerolinea,
    updated_by = excluded.updated_by,
    updated_at = excluded.updated_at
  returning * into result_row;

  return result_row;
end;
$$;

revoke all on function public.get_conciliacion_vuelo_airline_overrides() from public;
revoke all on function public.save_conciliacion_vuelo_airline_override(bigint, text, text) from public;
grant execute on function public.get_conciliacion_vuelo_airline_overrides() to authenticated;
grant execute on function public.save_conciliacion_vuelo_airline_override(bigint, text, text) to authenticated;
