-- Catálogo de matrículas utilizado por los manifiestos.
-- Fuente: Matrículas_manifiestos.xlsx / Hoja1.
-- La carga inicial se realiza después de crear esta tabla
-- mediante el bloque de importación indicado en las instrucciones de uso.

create table if not exists public.matriculas_manifiestos (
    id bigint generated by default as identity primary key,
    fila_origen integer not null unique,
    matricula text not null,
    aerolinea text not null,
    estatus text not null,
    tipo_de_aeronave text,
    tipo_de_aeronave_2 text,
    mlw_ton numeric(10,3),
    mtow_ton numeric(10,3),
    mzfw_ton numeric(10,3),
    promedio numeric(10,3),
    pasajeros integer not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint matriculas_manifiestos_fila_origen_ck
        check (fila_origen >= 2),
    constraint matriculas_manifiestos_estatus_ck
        check (estatus in ('ACTIVO', 'CHARTEROS')),
    constraint matriculas_manifiestos_mlw_ck
        check (mlw_ton is null or mlw_ton >= 0),
    constraint matriculas_manifiestos_mtow_ck
        check (mtow_ton is null or mtow_ton >= 0),
    constraint matriculas_manifiestos_mzfw_ck
        check (mzfw_ton is null or mzfw_ton >= 0),
    constraint matriculas_manifiestos_promedio_ck
        check (promedio is null or promedio >= 0),
    constraint matriculas_manifiestos_pasajeros_ck
        check (pasajeros >= 0)
);

comment on table public.matriculas_manifiestos is
    'Catálogo de matrículas y características de aeronaves para manifiestos.';
comment on column public.matriculas_manifiestos.fila_origen is
    'Número de fila original en la hoja Hoja1 del archivo Matrículas_manifiestos.xlsx.';
comment on column public.matriculas_manifiestos.matricula is
    'Matrícula normalizada sin espacios sobrantes; no se permiten matrículas repetidas.';
comment on column public.matriculas_manifiestos.mlw_ton is
    'Maximum Landing Weight, en toneladas.';
comment on column public.matriculas_manifiestos.mtow_ton is
    'Maximum Take-Off Weight, en toneladas.';
comment on column public.matriculas_manifiestos.mzfw_ton is
    'Maximum Zero Fuel Weight, en toneladas.';
comment on column public.matriculas_manifiestos.promedio is
    'Valor PROMEDIO del archivo fuente, en toneladas.';
comment on column public.matriculas_manifiestos.pasajeros is
    'Capacidad de pasajeros indicada en el archivo fuente.';

create index if not exists idx_matriculas_manifiestos_matricula
    on public.matriculas_manifiestos (matricula);

-- Si la tabla ya existía y la carga inicial tenía repetidos, conserva la fila
-- de mayor origen (la más reciente del Excel) antes de crear el índice único.
with ranked as (
    select
        id,
        row_number() over (
            partition by upper(btrim(replace(matricula, chr(160), ' ')))
            order by fila_origen desc, id desc
        ) as rn
    from public.matriculas_manifiestos
)
delete from public.matriculas_manifiestos m
using ranked r
where m.id = r.id
  and r.rn > 1;

update public.matriculas_manifiestos
set matricula = upper(btrim(replace(matricula, chr(160), ' '))),
    updated_at = now()
where matricula <> upper(btrim(replace(matricula, chr(160), ' ')));

create unique index if not exists uq_matriculas_manifiestos_matricula_normalizada
    on public.matriculas_manifiestos
    (upper(btrim(replace(matricula, chr(160), ' '))));

create index if not exists idx_matriculas_manifiestos_aerolinea
    on public.matriculas_manifiestos (aerolinea);

create index if not exists idx_matriculas_manifiestos_estatus
    on public.matriculas_manifiestos (estatus);

alter table public.matriculas_manifiestos enable row level security;

grant select on table public.matriculas_manifiestos to authenticated;
grant all on table public.matriculas_manifiestos to service_role;
grant usage, select, update on sequence public.matriculas_manifiestos_id_seq to service_role;

drop policy if exists "matriculas_manifiestos_read_authenticated"
    on public.matriculas_manifiestos;
create policy "matriculas_manifiestos_read_authenticated"
    on public.matriculas_manifiestos
    for select
    to authenticated
    using (true);
