-- Catálogos aislados para el área de Manifiestos.
-- Las modificaciones aquí no cambian public.airlines ni ningún catálogo principal.

create or replace function public.conci_catalogos_can_edit()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.user_roles ur
        where ur.user_id = auth.uid()
          and lower(trim(ur.role)) in (
              'admin', 'editor', 'superadmin', 'superuser', 'capturista'
          )
    );
$$;

revoke all on function public.conci_catalogos_can_edit() from public;
grant execute on function public.conci_catalogos_can_edit() to authenticated;

create table if not exists public.conciliacion_catalogo_aerolineas (
    id bigint generated by default as identity primary key,
    name text not null,
    iata text,
    aliases text[] not null default '{}',
    color text not null default '#6c757d',
    text_color text not null default '#ffffff',
    types text[] not null default '{}',
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists uq_conci_catalogo_aerolineas_name
    on public.conciliacion_catalogo_aerolineas (lower(btrim(name)));
create index if not exists idx_conci_catalogo_aerolineas_iata
    on public.conciliacion_catalogo_aerolineas (upper(btrim(iata)));

-- Copia inicial del catálogo vigente. Solo se ejecuta para nombres que aún no
-- existen en el catálogo aislado; después, los cambios quedan desacoplados.
do $$
begin
    if to_regclass('public.airlines') is not null then
        insert into public.conciliacion_catalogo_aerolineas
            (name, iata, aliases, color, text_color, types, active)
        select
            a.name,
            a.iata,
            coalesce(a.aliases, '{}'),
            coalesce(a.color, '#6c757d'),
            coalesce(a.text_color, '#ffffff'),
            coalesce(a.types, '{}'),
            coalesce(a.active, true)
        from public.airlines a
        where not exists (
            select 1
            from public.conciliacion_catalogo_aerolineas c
            where lower(btrim(c.name)) = lower(btrim(a.name))
        );
    end if;
end;
$$;

create or replace function public.conci_catalogos_set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists conciliacion_catalogo_aerolineas_updated_at
    on public.conciliacion_catalogo_aerolineas;
create trigger conciliacion_catalogo_aerolineas_updated_at
    before update on public.conciliacion_catalogo_aerolineas
    for each row execute function public.conci_catalogos_set_updated_at();

alter table public.conciliacion_catalogo_aerolineas enable row level security;
drop policy if exists "conci_airlines_read_authenticated"
    on public.conciliacion_catalogo_aerolineas;
create policy "conci_airlines_read_authenticated"
    on public.conciliacion_catalogo_aerolineas
    for select to authenticated
    using (true);

drop policy if exists "conci_airlines_write_area"
    on public.conciliacion_catalogo_aerolineas;
create policy "conci_airlines_write_area"
    on public.conciliacion_catalogo_aerolineas
    for all to authenticated
    using (public.conci_catalogos_can_edit())
    with check (public.conci_catalogos_can_edit());

grant select on table public.conciliacion_catalogo_aerolineas to authenticated;
grant insert, update, delete on table public.conciliacion_catalogo_aerolineas to authenticated;
grant usage, select on sequence public.conciliacion_catalogo_aerolineas_id_seq to authenticated;

-- La tabla de matrículas ya es exclusiva de Conciliación. Se agregan permisos
-- de escritura para el área, manteniendo lectura para usuarios autenticados.
drop policy if exists "matriculas_manifiestos_write_area"
    on public.matriculas_manifiestos;
create policy "matriculas_manifiestos_write_area"
    on public.matriculas_manifiestos
    for all to authenticated
    using (public.conci_catalogos_can_edit())
    with check (public.conci_catalogos_can_edit());

grant insert, update, delete on table public.matriculas_manifiestos to authenticated;
grant usage, select on sequence public.matriculas_manifiestos_id_seq to authenticated;

comment on table public.conciliacion_catalogo_aerolineas is
    'Catálogo de aerolíneas exclusivo para Conciliación/Manifiestos; no modifica public.airlines.';
